import { getLocale, type Locale } from "../../i18n";
import { securityText } from "./text";
const en = [
  "Select a valid agent and scope. Paths must be relative to the project directory.",
  "The project directory or source file is unavailable.",
  "There are no readable text files in the selected scope.",
  "Source files changed during the audit. Run the audit again against the current version.",
  "The agent’s response did not match the report format. Review the session or try again.",
  "Working tree changes require an accessible Git repository.",
  "The selected scope is too large. Select a smaller directory or file.",
  "This audit step timed out. Review the session or select a smaller scope.",
  "Choose an available model and a reasoning-effort level supported by that model.",
  "The model list could not be loaded. Check the local agent configuration and retry.",
];
const messages: Record<Exclude<Locale,"en">,string[]> = {
  "zh-CN":["请选择有效的助手和审计范围，路径须相对于项目目录。","项目目录或源码文件不可用。","所选范围内没有可读取的文本文件。","审计期间源码发生了变化，请对当前版本重新审计。","助手返回的内容不符合报告格式，请查看会话或重试。","审阅工作区变更需要可访问的 Git 仓库。","所选范围过大，请选择更小的目录或单个文件。","当前审计步骤已超时，请查看会话或缩小审计范围。","请选择可用的模型及该模型支持的思考程度。","无法加载模型列表，请检查本机助手配置后重试。"],
  "zh-TW":["請選擇有效的助理和稽核範圍，路徑須相對於專案目錄。","專案目錄或原始碼檔案無法使用。","所選範圍內沒有可讀取的文字檔案。","稽核期間原始碼發生變更，請對目前版本重新稽核。","助理回傳的內容不符合報告格式，請查看工作階段或重試。","審閱工作目錄變更需要可存取的 Git 儲存庫。","所選範圍過大，請選擇較小的目錄或單一檔案。","目前稽核步驟已逾時，請查看工作階段或縮小稽核範圍。","請選擇可用的模型及該模型支援的思考程度。","無法載入模型清單，請檢查本機助理設定後重試。"],
  de:["Wählen Sie einen gültigen Assistenten und Prüfumfang. Pfade müssen relativ zum Projektverzeichnis sein.","Das Projektverzeichnis oder die Quelldatei ist nicht verfügbar.","Der ausgewählte Bereich enthält keine lesbaren Textdateien.","Quelldateien wurden während der Prüfung geändert. Prüfen Sie die aktuelle Version erneut.","Die Antwort des Assistenten entspricht nicht dem Berichtsformat. Prüfen Sie die Sitzung oder versuchen Sie es erneut.","Änderungen im Arbeitsverzeichnis erfordern ein zugängliches Git-Repository.","Der ausgewählte Bereich ist zu groß. Wählen Sie ein kleineres Verzeichnis oder eine Datei.","Dieser Prüfschritt hat das Zeitlimit überschritten. Prüfen Sie die Sitzung oder verkleinern Sie den Umfang.","Wählen Sie ein verfügbares Modell und eine von diesem Modell unterstützte Denkintensität.","Die Modellliste konnte nicht geladen werden. Prüfen Sie die Konfiguration des lokalen Assistenten und versuchen Sie es erneut."],
  es:["Seleccione un asistente y un alcance válidos. Las rutas deben ser relativas al directorio del proyecto.","El directorio del proyecto o el archivo fuente no está disponible.","No hay archivos de texto legibles en el alcance seleccionado.","Los archivos fuente cambiaron durante la auditoría. Audite de nuevo la versión actual.","La respuesta del asistente no coincide con el formato del informe. Revise la sesión o vuelva a intentarlo.","Los cambios del árbol de trabajo requieren un repositorio Git accesible.","El alcance seleccionado es demasiado grande. Seleccione un directorio más pequeño o un archivo.","Este paso de auditoría agotó el tiempo disponible. Revise la sesión o reduzca el alcance.","Seleccione un modelo disponible y un nivel de esfuerzo de razonamiento compatible con él.","No se pudo cargar la lista de modelos. Revise la configuración del asistente local y vuelva a intentarlo."],
  fr:["Sélectionnez un assistant et un périmètre valides. Les chemins doivent être relatifs au dossier du projet.","Le dossier du projet ou le fichier source est indisponible.","Le périmètre sélectionné ne contient aucun fichier texte lisible.","Des fichiers sources ont changé pendant l’audit. Relancez l’audit sur la version actuelle.","La réponse de l’assistant ne respecte pas le format du rapport. Consultez la session ou réessayez.","L’examen des modifications de l’arbre de travail nécessite un dépôt Git accessible.","Le périmètre sélectionné est trop large. Choisissez un dossier plus petit ou un fichier.","Cette étape a dépassé le délai imparti. Consultez la session ou réduisez le périmètre.","Choisissez un modèle disponible et un niveau d’effort de raisonnement qu’il prend en charge.","Impossible de charger la liste des modèles. Vérifiez la configuration de l’assistant local, puis réessayez."],
  ja:["有効なアシスタントと監査範囲を選択してください。パスはプロジェクトディレクトリからの相対パスで指定します。","プロジェクトディレクトリまたはソースファイルを利用できません。","選択した範囲に読み取り可能なテキストファイルがありません。","監査中にソースファイルが変更されました。現在のバージョンで再度監査してください。","アシスタントの応答がレポート形式に一致しません。セッションを確認するか、再試行してください。","作業ツリーの変更を確認するには、アクセス可能な Git リポジトリが必要です。","選択した範囲が大きすぎます。より小さなディレクトリまたはファイルを選択してください。","この監査ステップはタイムアウトしました。セッションを確認するか、監査範囲を縮小してください。","利用可能なモデルと、そのモデルが対応する思考レベルを選択してください。","モデル一覧を読み込めませんでした。ローカルアシスタントの設定を確認して再試行してください。"],
  ko:["유효한 도우미와 감사 범위를 선택하세요. 프로젝트 디렉터리를 기준으로 상대 경로를 지정해야 합니다.","프로젝트 디렉터리 또는 소스 파일을 사용할 수 없습니다.","선택한 범위에 읽을 수 있는 텍스트 파일이 없습니다.","감사 중 소스 파일이 변경되었습니다. 현재 버전을 다시 감사하세요.","도우미의 응답이 보고서 형식과 일치하지 않습니다. 세션을 확인하거나 다시 시도하세요.","작업 트리 변경 사항을 검토하려면 접근 가능한 Git 저장소가 필요합니다.","선택한 범위가 너무 큽니다. 더 작은 디렉터리나 파일을 선택하세요.","이 감사 단계의 제한 시간이 초과되었습니다. 세션을 확인하거나 범위를 줄이세요.","사용 가능한 모델과 해당 모델이 지원하는 추론 수준을 선택하세요.","모델 목록을 불러오지 못했습니다. 로컬 도우미 설정을 확인한 후 다시 시도하세요."],
  "pt-BR":["Selecione um assistente e um escopo válidos. Os caminhos devem ser relativos ao diretório do projeto.","O diretório do projeto ou o arquivo-fonte está indisponível.","Não há arquivos de texto legíveis no escopo selecionado.","Os arquivos-fonte mudaram durante a auditoria. Execute a auditoria novamente na versão atual.","A resposta do assistente não corresponde ao formato do relatório. Revise a sessão ou tente novamente.","As alterações na árvore de trabalho exigem um repositório Git acessível.","O escopo selecionado é muito grande. Selecione um diretório menor ou um arquivo.","Esta etapa da auditoria excedeu o tempo limite. Revise a sessão ou reduza o escopo.","Selecione um modelo disponível e um nível de esforço de raciocínio compatível com ele.","Não foi possível carregar a lista de modelos. Verifique a configuração do assistente local e tente novamente."],
  ru:["Выберите допустимого помощника и область проверки. Пути должны быть относительными к каталогу проекта.","Каталог проекта или исходный файл недоступен.","В выбранной области нет доступных для чтения текстовых файлов.","Исходные файлы изменились во время аудита. Повторите аудит текущей версии.","Ответ помощника не соответствует формату отчёта. Проверьте сеанс или повторите попытку.","Для проверки изменений рабочего дерева нужен доступный репозиторий Git.","Выбранная область слишком велика. Выберите каталог меньшего размера или отдельный файл.","Время выполнения этого этапа истекло. Проверьте сеанс или уменьшите область проверки.","Выберите доступную модель и поддерживаемый ею уровень усилий рассуждения.","Не удалось загрузить список моделей. Проверьте настройки локального помощника и повторите попытку."],
  vi:["Chọn trợ lý và phạm vi hợp lệ. Đường dẫn phải tương đối so với thư mục dự án.","Không thể truy cập thư mục dự án hoặc tệp mã nguồn.","Không có tệp văn bản nào đọc được trong phạm vi đã chọn.","Mã nguồn đã thay đổi trong khi kiểm toán. Hãy kiểm toán lại phiên bản hiện tại.","Phản hồi của trợ lý không đúng định dạng báo cáo. Hãy xem phiên làm việc hoặc thử lại.","Đánh giá thay đổi trong cây làm việc cần một kho Git có thể truy cập.","Phạm vi đã chọn quá lớn. Hãy chọn thư mục nhỏ hơn hoặc một tệp.","Bước kiểm toán này đã hết thời gian. Hãy xem phiên làm việc hoặc thu hẹp phạm vi.","Chọn một mô hình khả dụng và mức độ suy luận mà mô hình đó hỗ trợ.","Không thể tải danh sách mô hình. Hãy kiểm tra cấu hình trợ lý trên máy rồi thử lại."],
};
const evidenceErrors: Record<Locale, string> = {
  en: "Source evidence could not be verified. The retained upstream report is available for review, but this audit failed validation.",
  "zh-CN": "源码证据未通过校验。上游报告已保留供核查，本次审计未通过验证。",
  "zh-TW": "原始碼證據未通過校驗。上游報告已保留供查核，本次稽核未通過驗證。",
  de: "Die Quellcodebelege konnten nicht verifiziert werden. Der aufbewahrte Upstream-Bericht kann geprüft werden; diese Prüfung hat die Validierung jedoch nicht bestanden.",
  es: "No se pudieron verificar las pruebas del código fuente. El informe original se conserva para su revisión, pero esta auditoría no superó la validación.",
  fr: "Les preuves tirées du code source n’ont pas pu être vérifiées. Le rapport d’origine reste consultable, mais cet audit n’a pas passé la validation.",
  ja: "ソースコードの証拠を検証できませんでした。確認用に上流のレポートを保存していますが、この監査は検証に失敗しました。",
  ko: "소스 코드 증거를 검증하지 못했습니다. 검토를 위해 원본 보고서를 보관했지만 이 감사는 검증을 통과하지 못했습니다.",
  "pt-BR": "Não foi possível verificar as evidências do código-fonte. O relatório original foi preservado para revisão, mas esta auditoria não passou na validação.",
  ru: "Не удалось проверить доказательства из исходного кода. Исходный отчёт сохранён для проверки, но этот аудит не прошёл валидацию.",
  vi: "Không thể xác minh bằng chứng từ mã nguồn. Báo cáo gốc được giữ lại để kiểm tra, nhưng cuộc kiểm toán này chưa vượt qua bước xác minh.",
};
export function auditError(error: unknown): string {
  const raw = String(error);
  const selectionError = /security_invalid:(model|effort|selection)/.test(raw);
  const code=String(error).match(/security_[a-z_]+/)?.[0]??"";
  if(code === "security_evidence_mismatch") return evidenceErrors[getLocale()];
  const index=selectionError ? 8 : ({security_invalid:0,security_missing_root:1,security_source_missing:1,security_source_unavailable:1,security_empty_scope:2,security_source_changed:3,security_invalid_output:4,security_git_required:5,security_git_failed:5,security_scope_too_large:6,security_context_too_large:6,security_timeout:7,security_models_unavailable:9} as Record<string,number>)[code];
  if(index==null)return securityText("error");
  const locale=getLocale();return locale==="en"?en[index]:messages[locale][index];
}
