import { getLocale, type Locale } from "../../i18n";

const en = {
  title: "Code audit", intro: "A shared security review workflow using your local coding agent.",
  new: "New audit", history: "Audit history", start: "Start audit", agent: "Local agent", scope: "Scope", path: "Relative path",
  repository: "Whole repository", "working-tree": "Working tree changes", pathScope: "Directory or file",
  running: "Running", waiting: "Permission or input required", completed: "Completed", partial: "Partial coverage",
  failed: "Failed", canceled: "Canceled", interrupted: "Interrupted", threat: "Threat model", discovery: "Finding discovery",
  validation: "Evidence review", report: "Report", conversation: "Agent session", findings: "Findings", coverage: "Coverage",
  reviewed: "Files reported reviewed", gaps: "Coverage and evidence gaps", excluded: "Excluded or unavailable files",
  empty: "No audits yet.", noFindings: "No findings recorded.", export: "Export report", config: "Uses this machine’s agent login and configuration. No separate model API setup is needed.",
  note: "Static review only. Reported coverage does not guarantee that every vulnerability was found. Dynamic exploitation is not performed.",
  waitingHint: "Open the agent session to review the pending request. The audit continues when it is resolved.",
  source: "Entry point", sink: "Sensitive operation", preconditions: "Preconditions", impact: "Impact", recommendation: "Recommendation", evidence: "Source evidence",
  candidate: "Unconfirmed", validated: "Statically validated", rejected: "Rejected", critical: "Critical", high: "High", medium: "Medium", low: "Low",
  error: "The audit could not proceed. Review the details or the agent session.", missingSession: "The audit session is no longer available.",
};
type Key = keyof typeof en;
const keys = Object.keys(en) as Key[];
// Each locale follows the same key order; these are presentation strings, not workflow configuration.
const translations: Record<Exclude<Locale,"en">, string[]> = {
  "zh-CN": ["代码审计","使用本机编程助手，执行统一的安全审计流程。","新建审计","审计历史","开始审计","本机助手","审计范围","相对路径","整个仓库","工作区变更","目录或文件","执行中","等待权限或输入","已完成","部分覆盖","失败","已取消","已中断","威胁模型","发现问题","证据复核","报告","助手会话","发现的问题","覆盖情况","助手报告已审阅的文件","覆盖与证据缺口","已排除或无法读取的文件","暂无审计记录。","尚未记录问题。","导出报告","沿用本机助手的登录和配置，无需单独配置模型 API。","仅执行静态审阅。报告中的覆盖情况不保证发现全部漏洞，也不代表已进行动态漏洞复现。","请打开助手会话处理待确认请求，处理后审计将继续。","输入入口","敏感操作","前置条件","影响","修复建议","源码证据","待确认","静态复核通过","已排除","严重","高","中","低","审计无法继续，请查看详情或助手会话。","审计会话已不可用。"],
  "zh-TW": ["程式碼稽核","使用本機程式設計助理，執行統一的安全稽核流程。","新增稽核","稽核記錄","開始稽核","本機助理","稽核範圍","相對路徑","整個儲存庫","工作目錄變更","目錄或檔案","執行中","等待權限或輸入","已完成","部分涵蓋","失敗","已取消","已中斷","威脅模型","探索問題","證據複核","報告","助理工作階段","發現的問題","涵蓋情況","助理回報已審閱的檔案","涵蓋與證據缺口","已排除或無法讀取的檔案","尚無稽核記錄。","尚未記錄問題。","匯出報告","沿用本機助理的登入和設定，無須另行設定模型 API。","僅執行靜態審閱。報告中的涵蓋情況不保證發現所有漏洞，也不代表已進行動態漏洞重現。","請開啟助理工作階段處理待確認請求，處理後稽核將繼續。","輸入入口","敏感操作","前置條件","影響","修復建議","原始碼證據","待確認","靜態複核通過","已排除","嚴重","高","中","低","稽核無法繼續，請查看詳細資訊或助理工作階段。","稽核工作階段已無法使用。"],
  de: ["Codeprüfung","Ein einheitlicher Sicherheitsprüfprozess mit Ihrem lokalen Programmierassistenten.","Neue Prüfung","Prüfverlauf","Prüfung starten","Lokaler Assistent","Umfang","Relativer Pfad","Gesamtes Repository","Änderungen im Arbeitsverzeichnis","Verzeichnis oder Datei","Wird ausgeführt","Berechtigung oder Eingabe erforderlich","Abgeschlossen","Teilweise abgedeckt","Fehlgeschlagen","Abgebrochen","Unterbrochen","Bedrohungsmodell","Schwachstellensuche","Evidenzprüfung","Bericht","Assistentensitzung","Befunde","Abdeckung","Als geprüft gemeldete Dateien","Lücken bei Abdeckung und Evidenz","Ausgeschlossene oder nicht verfügbare Dateien","Noch keine Prüfungen.","Keine Befunde erfasst.","Bericht exportieren","Verwendet die Anmeldung und Konfiguration des lokalen Assistenten. Keine separate Modell-API erforderlich.","Nur statische Prüfung. Die gemeldete Abdeckung garantiert nicht, dass alle Schwachstellen erkannt wurden. Es werden keine dynamischen Exploits ausgeführt.","Öffnen Sie die Assistentensitzung und bearbeiten Sie die ausstehende Anfrage. Danach wird die Prüfung fortgesetzt.","Einstiegspunkt","Sicherheitsrelevante Operation","Voraussetzungen","Auswirkung","Empfehlung","Quellcodebeleg","Unbestätigt","Statisch bestätigt","Verworfen","Kritisch","Hoch","Mittel","Niedrig","Die Prüfung konnte nicht fortgesetzt werden. Prüfen Sie die Details oder die Assistentensitzung.","Die Prüfsitzung ist nicht mehr verfügbar."],
  es: ["Auditoría de código","Un proceso de revisión de seguridad unificado con su asistente de programación local.","Nueva auditoría","Historial de auditorías","Iniciar auditoría","Asistente local","Alcance","Ruta relativa","Todo el repositorio","Cambios del árbol de trabajo","Directorio o archivo","En curso","Se requiere permiso o información","Completada","Cobertura parcial","Fallida","Cancelada","Interrumpida","Modelo de amenazas","Búsqueda de vulnerabilidades","Revisión de evidencias","Informe","Sesión del asistente","Hallazgos","Cobertura","Archivos que el asistente declara revisados","Carencias de cobertura y evidencia","Archivos excluidos o no disponibles","Aún no hay auditorías.","No hay hallazgos registrados.","Exportar informe","Utiliza el inicio de sesión y la configuración del asistente local. No requiere configurar una API de modelos adicional.","Solo revisión estática. La cobertura declarada no garantiza que se hayan detectado todas las vulnerabilidades. No se ejecutan pruebas de explotación dinámica.","Abra la sesión del asistente para atender la solicitud pendiente. La auditoría continuará cuando se resuelva.","Punto de entrada","Operación sensible","Condiciones previas","Impacto","Recomendación","Evidencia del código fuente","Sin confirmar","Validado estáticamente","Descartado","Crítica","Alta","Media","Baja","La auditoría no pudo continuar. Consulte los detalles o la sesión del asistente.","La sesión de auditoría ya no está disponible."],
  fr: ["Audit de code","Un processus commun d’audit de sécurité utilisant votre assistant de programmation local.","Nouvel audit","Historique des audits","Lancer l’audit","Assistant local","Périmètre","Chemin relatif","Dépôt entier","Modifications de l’arbre de travail","Dossier ou fichier","En cours","Autorisation ou saisie requise","Terminé","Couverture partielle","Échec","Annulé","Interrompu","Modèle de menaces","Recherche de vulnérabilités","Vérification des preuves","Rapport","Session de l’assistant","Résultats","Couverture","Fichiers déclarés examinés","Lacunes de couverture et de preuve","Fichiers exclus ou indisponibles","Aucun audit pour le moment.","Aucun résultat enregistré.","Exporter le rapport","Utilise la connexion et la configuration de l’assistant local. Aucune API de modèle supplémentaire à configurer.","Analyse statique uniquement. La couverture déclarée ne garantit pas la détection de toutes les vulnérabilités. Aucun exploit n’est exécuté.","Ouvrez la session de l’assistant pour traiter la demande en attente. L’audit reprendra ensuite.","Point d’entrée","Opération sensible","Conditions préalables","Impact","Recommandation","Preuve dans le code source","Non confirmé","Validé statiquement","Écarté","Critique","Élevée","Moyenne","Faible","L’audit n’a pas pu continuer. Consultez les détails ou la session de l’assistant.","La session d’audit n’est plus disponible."],
  ja: ["コード監査","ローカルのコーディングアシスタントを使い、共通のセキュリティ監査手順を実行します。","新規監査","監査履歴","監査を開始","ローカルアシスタント","監査範囲","相対パス","リポジトリ全体","作業ツリーの変更","ディレクトリまたはファイル","実行中","権限の承認または入力が必要","完了","一部のみ確認済み","失敗","キャンセル済み","中断","脅威モデル","問題の検出","証拠の検証","レポート","アシスタントのセッション","検出結果","確認範囲","アシスタントが確認済みと報告したファイル","確認範囲と証拠の不足","除外または読み取り不可のファイル","監査履歴はありません。","検出結果は記録されていません。","レポートをエクスポート","ローカルアシスタントのログインと設定を引き継ぎます。モデル API の個別設定は不要です。","静的なレビューのみを行います。報告された確認範囲は、すべての脆弱性の検出を保証するものではありません。動的な攻撃の再現は行いません。","アシスタントのセッションを開き、保留中のリクエストに対応してください。対応後に監査が続行されます。","入力元","機密性の高い操作","前提条件","影響","修正案","ソースコードの証拠","未確認","静的検証済み","対象外と判定","緊急","高","中","低","監査を続行できませんでした。詳細またはアシスタントのセッションを確認してください。","監査セッションは利用できなくなりました。"],
  ko: ["코드 감사","로컬 코딩 도우미로 공통 보안 감사 절차를 실행합니다.","새 감사","감사 기록","감사 시작","로컬 도우미","감사 범위","상대 경로","전체 저장소","작업 트리 변경 사항","디렉터리 또는 파일","실행 중","권한 승인 또는 입력 필요","완료","일부 범위만 검토됨","실패","취소됨","중단됨","위협 모델","문제 발견","증거 검토","보고서","도우미 세션","발견 사항","검토 범위","도우미가 검토했다고 보고한 파일","검토 범위 및 증거의 공백","제외되거나 읽을 수 없는 파일","아직 감사 기록이 없습니다.","기록된 발견 사항이 없습니다.","보고서 내보내기","로컬 도우미의 로그인과 설정을 사용합니다. 별도의 모델 API 설정이 필요하지 않습니다.","정적 검토만 수행합니다. 보고된 검토 범위가 모든 취약점의 발견을 보장하지는 않습니다. 동적 공격 재현은 수행하지 않습니다.","도우미 세션을 열어 대기 중인 요청을 처리하세요. 처리 후 감사가 계속됩니다.","입력 지점","민감한 작업","전제 조건","영향","수정 권고","소스 코드 증거","미확인","정적 검증 완료","제외됨","치명적","높음","중간","낮음","감사를 계속할 수 없습니다. 세부 정보나 도우미 세션을 확인하세요.","감사 세션을 더 이상 사용할 수 없습니다."],
  "pt-BR": ["Auditoria de código","Um fluxo unificado de revisão de segurança com seu assistente de programação local.","Nova auditoria","Histórico de auditorias","Iniciar auditoria","Assistente local","Escopo","Caminho relativo","Repositório inteiro","Alterações na árvore de trabalho","Diretório ou arquivo","Em execução","Permissão ou entrada necessária","Concluída","Cobertura parcial","Falhou","Cancelada","Interrompida","Modelo de ameaças","Descoberta de vulnerabilidades","Revisão de evidências","Relatório","Sessão do assistente","Achados","Cobertura","Arquivos que o assistente declarou revisados","Lacunas de cobertura e evidência","Arquivos excluídos ou indisponíveis","Nenhuma auditoria ainda.","Nenhum achado registrado.","Exportar relatório","Usa o login e a configuração do assistente local. Não é necessário configurar outra API de modelos.","Apenas revisão estática. A cobertura declarada não garante que todas as vulnerabilidades foram encontradas. Não são executadas explorações dinâmicas.","Abra a sessão do assistente para atender à solicitação pendente. A auditoria continuará após a resolução.","Ponto de entrada","Operação sensível","Pré-condições","Impacto","Recomendação","Evidência no código-fonte","Não confirmado","Validado estaticamente","Descartado","Crítica","Alta","Média","Baixa","A auditoria não pôde continuar. Consulte os detalhes ou a sessão do assistente.","A sessão de auditoria não está mais disponível."],
  ru: ["Аудит кода","Единый процесс проверки безопасности с локальным помощником по программированию.","Новый аудит","История аудитов","Начать аудит","Локальный помощник","Область проверки","Относительный путь","Весь репозиторий","Изменения рабочего дерева","Каталог или файл","Выполняется","Требуется разрешение или ввод","Завершён","Частичное покрытие","Ошибка","Отменён","Прерван","Модель угроз","Поиск уязвимостей","Проверка доказательств","Отчёт","Сеанс помощника","Находки","Покрытие","Файлы, отмеченные помощником как проверенные","Пробелы в покрытии и доказательствах","Исключённые или недоступные файлы","Аудитов пока нет.","Находок пока нет.","Экспорт отчёта","Используются вход в учётную запись и настройки локального помощника. Отдельная настройка API модели не требуется.","Только статическая проверка. Заявленное покрытие не гарантирует обнаружения всех уязвимостей. Динамическое воспроизведение атак не выполняется.","Откройте сеанс помощника и обработайте ожидающий запрос. После этого аудит продолжится.","Точка входа","Критичная операция","Предварительные условия","Влияние","Рекомендация","Доказательство в исходном коде","Не подтверждено","Подтверждено статически","Отклонено","Критическая","Высокая","Средняя","Низкая","Не удалось продолжить аудит. Проверьте подробности или сеанс помощника.","Сеанс аудита больше недоступен."],
  vi: ["Kiểm toán mã nguồn","Quy trình đánh giá bảo mật thống nhất với trợ lý lập trình trên máy.","Tạo cuộc kiểm toán","Lịch sử kiểm toán","Bắt đầu kiểm toán","Trợ lý trên máy","Phạm vi","Đường dẫn tương đối","Toàn bộ kho mã","Thay đổi trong cây làm việc","Thư mục hoặc tệp","Đang chạy","Cần cấp quyền hoặc nhập thông tin","Đã hoàn tất","Mới đánh giá một phần","Thất bại","Đã hủy","Bị gián đoạn","Mô hình mối đe dọa","Phát hiện vấn đề","Rà soát bằng chứng","Báo cáo","Phiên trợ lý","Vấn đề phát hiện","Phạm vi đã đánh giá","Tệp được trợ lý báo cáo là đã xem xét","Phần chưa đánh giá và bằng chứng còn thiếu","Tệp bị loại trừ hoặc không đọc được","Chưa có cuộc kiểm toán nào.","Chưa ghi nhận vấn đề nào.","Xuất báo cáo","Sử dụng thông tin đăng nhập và cấu hình của trợ lý trên máy. Không cần cấu hình API mô hình riêng.","Chỉ đánh giá tĩnh. Phạm vi được báo cáo không bảo đảm đã tìm thấy mọi lỗ hổng. Không thực hiện khai thác động.","Mở phiên trợ lý để xử lý yêu cầu đang chờ. Cuộc kiểm toán sẽ tiếp tục sau khi yêu cầu được giải quyết.","Điểm đầu vào","Thao tác nhạy cảm","Điều kiện tiên quyết","Tác động","Khuyến nghị","Bằng chứng mã nguồn","Chưa xác nhận","Đã xác minh tĩnh","Đã loại trừ","Nghiêm trọng","Cao","Trung bình","Thấp","Không thể tiếp tục kiểm toán. Hãy xem chi tiết hoặc phiên trợ lý.","Phiên kiểm toán không còn khả dụng."],
};
const upstreamKeys = ["preflight", "attack_path", "legacy", "checkpoint", "checks", "threat_surfaces", "review_receipts", "candidate_findings", "validated_findings", "report_artifacts", "informational"];
const upstreamText: Record<Locale, string[]> = {
  en: ["Preflight", "Attack path analysis", "Legacy audit · This record did not use the Codex Security workflow.", "This is scan progress, not a completed report. Retained findings and checkpoints do not establish full coverage.", "Checks", "Threat surfaces", "Review receipts", "Candidate findings", "Validated findings", "Report artifacts", "Informational"],
  "zh-CN": ["运行前检查", "攻击路径分析", "旧版审计 · 此记录未使用 Codex Security 流程。", "这里显示扫描进度，尚不是最终报告。已保存的问题和检查点不代表审计范围已全部覆盖。", "检查项", "威胁面", "审查记录", "候选问题", "已验证问题", "报告产物", "信息"],
  "zh-TW": ["執行前檢查", "攻擊路徑分析", "舊版稽核 · 此記錄未使用 Codex Security 流程。", "此處顯示掃描進度，尚非最終報告。已儲存的問題與檢查點不代表已完整涵蓋稽核範圍。", "檢查項目", "威脅面", "審查記錄", "候選問題", "已驗證問題", "報告產物", "資訊"],
  de: ["Vorprüfung", "Analyse der Angriffspfade", "Frühere Prüfung · Dieser Datensatz entstand ohne den Codex Security-Prozess.", "Dies ist der Scanfortschritt, kein Abschlussbericht. Gespeicherte Befunde und Zwischenstände belegen keine vollständige Abdeckung.", "Prüfpunkte", "Bedrohungsflächen", "Prüfnachweise", "Mögliche Befunde", "Validierte Befunde", "Berichtsartefakte", "Information"],
  es: ["Comprobaciones previas", "Análisis de rutas de ataque", "Auditoría anterior · Este registro no utilizó el proceso de Codex Security.", "Se muestra el progreso del análisis, no un informe final. Los hallazgos y puntos de control guardados no acreditan una cobertura completa.", "Comprobaciones", "Superficies de amenaza", "Registros de revisión", "Hallazgos candidatos", "Hallazgos validados", "Archivos del informe", "Informativa"],
  fr: ["Vérifications préalables", "Analyse des chemins d’attaque", "Ancien audit · Cet enregistrement n’a pas utilisé le processus Codex Security.", "Il s’agit de la progression de l’analyse, pas du rapport final. Les résultats et points de contrôle enregistrés ne prouvent pas une couverture complète.", "Vérifications", "Surfaces de menace", "Traces de vérification", "Résultats potentiels", "Résultats validés", "Fichiers du rapport", "Information"],
  ja: ["実行前チェック", "攻撃経路の分析", "旧方式の監査 · この記録では Codex Security の手順を使用していません。", "ここにはスキャンの進捗が表示されます。最終レポートではありません。保存済みの検出結果やチェックポイントは、監査範囲全体の確認を示すものではありません。", "確認項目", "脅威の対象領域", "レビュー記録", "問題の候補", "検証済みの問題", "レポート成果物", "情報"],
  ko: ["실행 전 점검", "공격 경로 분석", "이전 방식의 감사 · 이 기록에는 Codex Security 절차가 사용되지 않았습니다.", "현재 표시된 내용은 스캔 진행 상황이며 최종 보고서가 아닙니다. 저장된 발견 사항과 체크포인트만으로 감사 범위 전체를 검토했다고 볼 수는 없습니다.", "점검 항목", "위협 영역", "검토 기록", "후보 발견 사항", "검증된 발견 사항", "보고서 산출물", "정보"],
  "pt-BR": ["Verificações preliminares", "Análise dos caminhos de ataque", "Auditoria anterior · Este registro não utilizou o processo do Codex Security.", "Este é o progresso da análise, não o relatório final. Os achados e pontos de controle salvos não comprovam cobertura completa.", "Verificações", "Superfícies de ameaça", "Registros de revisão", "Possíveis achados", "Achados validados", "Arquivos do relatório", "Informativa"],
  ru: ["Предварительная проверка", "Анализ путей атаки", "Аудит прежнего формата · Эта запись создана без процесса Codex Security.", "Здесь показан ход сканирования, а не итоговый отчёт. Сохранённые находки и контрольные точки не подтверждают полноту проверки.", "Проверки", "Поверхности угроз", "Записи проверки", "Потенциальные находки", "Проверенные находки", "Артефакты отчёта", "Информационная"],
  vi: ["Kiểm tra trước khi chạy", "Phân tích đường tấn công", "Kiểm toán theo quy trình cũ · Bản ghi này không sử dụng quy trình Codex Security.", "Đây là tiến độ quét, chưa phải báo cáo cuối cùng. Các phát hiện và điểm kiểm tra đã lưu không chứng minh rằng toàn bộ phạm vi đã được kiểm tra.", "Mục kiểm tra", "Bề mặt đe dọa", "Bản ghi kiểm tra", "Phát hiện cần xác minh", "Phát hiện đã xác minh", "Tệp báo cáo", "Thông tin"],
};
const upstreamNotes: Record<Locale, string> = {
  en: "Runs the bundled Codex Security skills and scan tools. Open Agent session to inspect tool calls and answer permission requests; the report shows retained evidence and coverage limits.",
  "zh-CN": "执行内置 Codex Security 技能与扫描工具。在“助手会话”中查看工具调用并处理权限请求；报告展示保存的证据和覆盖限制。",
  "zh-TW": "執行內建 Codex Security 技能與掃描工具。在「助理工作階段」中查看工具呼叫並處理權限請求；報告呈現已儲存的證據與涵蓋範圍限制。",
  de: "Führt die mitgelieferten Codex Security-Skills und Scan-Werkzeuge aus. In der Agent-Sitzung können Sie Werkzeugaufrufe prüfen und Berechtigungsanfragen beantworten. Der Bericht zeigt gespeicherte Belege und Grenzen der Abdeckung.",
  es: "Ejecuta las habilidades y herramientas de análisis de Codex Security incluidas. Abra la sesión del agente para revisar las llamadas a herramientas y responder a las solicitudes de permiso. El informe muestra las pruebas guardadas y los límites de cobertura.",
  fr: "Exécute les compétences et outils d’analyse Codex Security intégrés. Ouvrez la session de l’agent pour examiner les appels d’outils et répondre aux demandes d’autorisation. Le rapport présente les preuves conservées et les limites de couverture.",
  ja: "同梱の Codex Security スキルとスキャンツールを実行します。エージェントのセッションでツール呼び出しを確認し、権限リクエストに応答してください。レポートには保存された証拠と監査範囲の制限が表示されます。",
  ko: "내장된 Codex Security 스킬과 스캔 도구를 실행합니다. 에이전트 세션에서 도구 호출을 확인하고 권한 요청에 응답할 수 있습니다. 보고서에는 저장된 증거와 검토 범위의 한계가 표시됩니다.",
  "pt-BR": "Executa as habilidades e ferramentas de análise do Codex Security incluídas. Abra a sessão do agente para examinar as chamadas de ferramentas e responder às solicitações de permissão. O relatório apresenta as evidências salvas e os limites da cobertura.",
  ru: "Запускает встроенные навыки и инструменты сканирования Codex Security. В сеансе агента можно просмотреть вызовы инструментов и ответить на запросы разрешений. Отчёт содержит сохранённые доказательства и ограничения охвата проверки.",
  vi: "Chạy các kỹ năng và công cụ quét Codex Security tích hợp. Mở phiên trợ lý để xem các lệnh gọi công cụ và xử lý yêu cầu cấp quyền. Báo cáo trình bày bằng chứng đã lưu và giới hạn phạm vi kiểm tra.",
};
export function securityText(key: Key | string, locale: Locale = getLocale()): string {
  if (key === "upstreamNote") return upstreamNotes[locale];
  if (key === "threat_model") key = "threat";
  if (key === "reporting") key = "report";
  const upstreamIndex = upstreamKeys.indexOf(key);
  if (upstreamIndex >= 0) return upstreamText[locale][upstreamIndex];
  if (!(key in en)) return key;
  const index = keys.indexOf(key as Key);
  return locale === "en" ? en[key as Key] : translations[locale][index] ?? en[key as Key];
}
